name: easy_loading_animations
description: A collection of smart loading animations with no extra dependency written in pure dart.
version: 1.0.0
homepage: https://github.com/ZainUrRehmanKhan/easy-loading-animations

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0

flutter: